server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true
resilience4j:
  retry:
    instances:
      foo-bar:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      foo-bar:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs
  override-server-url: true