services:
  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
          - arruda-network

  naming-server:
    image: felipearruda15/naming-server:latest
    ports:
      - 8761:8761
    depends_on:
      - zipkin-server
    networks:
      - arruda-network

  db-book:
    image: mysql:9.3.0
    restart: always
    ports:
      - 3310:3306
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: arruda123
      MYSQL_PASSWORD: arruda123
      MYSQL_DATABASE: book_service
    networks:
      - arruda-network

  db-exchange:
    image: mysql:9.3.0
    restart: always
    ports:
      - 3308:3306
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: arruda123
      MYSQL_PASSWORD: arruda123
      MYSQL_DATABASE: exchange_service
    networks:
      - arruda-network

  api-gateway:
    image: felipearruda15/api-gateway:latest
    ports:
      - 8765:8765
    restart: always
    depends_on:
      - zipkin-server
      - naming-server
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - arruda-network

  exchange-service:
    image: felipearruda15/exchange-service:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db-exchange:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: arruda123
      SPRING_DATASOURCE_PASSWORD: arruda123
    depends_on:
      - zipkin-server
      - naming-server
      - db-exchange
    networks:
      - arruda-network

  book-service:
    image: felipearruda15/book-service:latest
    ports:
      - 8100:8100
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db-book:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: arruda123
      SPRING_DATASOURCE_PASSWORD: arruda123
    depends_on:
      - zipkin-server
      - naming-server
      - db-exchange
    networks:
      - arruda-network

networks:
  arruda-network:
    name: arruda-network
    driver: bridge