services:
  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
          - arruda-network
  naming-server:
    image: felipearruda15/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    depends_on:
      - zipkin-server
    networks:
      - arruda-network
  api-gateway:
    image: felipearruda15/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    restart: always
    depends_on:
      - zipkin-server
      - naming-server
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - arruda-network
networks:
  arruda-network:
    name: arruda-network
    driver: bridge